package com.ibrahim.sepreader;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.view.*;import android.view.inputmethod.EditorInfo;import android.webkit.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 private LinearLayout root, content; private ScrollView sc; private WebView web; private EditText search; private TextView star; private boolean dark=false; private final String HOME="https://plato.stanford.edu/"; private android.content.SharedPreferences prefs;
 private static final String SEP="\u0001"; // title/url separator within one stored entry
 int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,float size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(dark?Color.WHITE:Color.rgb(32,33,36));t.setPadding(dp(18),dp(10),dp(18),dp(10));return t;}
 @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("sep",0); dark=prefs.getBoolean("dark",false); buildHome();}
 void buildHome(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(dark?Color.rgb(18,18,18):Color.rgb(250,248,243));
  LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL); TextView title=tv("SEP Reader",22);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setOnClickListener(v->goHome());bar.addView(title,new LinearLayout.LayoutParams(0,dp(64),1));
  star=tv("☆",22);star.setGravity(Gravity.CENTER);star.setOnClickListener(v->toggleBookmark());bar.addView(star,new LinearLayout.LayoutParams(dp(52),dp(64)));
  TextView theme=tv(dark?"☀":"☾",24);theme.setGravity(Gravity.CENTER);theme.setOnClickListener(v->{dark=!dark;prefs.edit().putBoolean("dark",dark).apply();buildHome();});bar.addView(theme,new LinearLayout.LayoutParams(dp(58),dp(64)));root.addView(bar);
  search=new EditText(this);search.setHint("Search philosophy…");search.setSingleLine();search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);search.setPadding(dp(18),0,dp(18),0);root.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));search.setOnEditorActionListener((v,a,e)->{openSearch(search.getText().toString());return true;});
  content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc=new ScrollView(this);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
  TextView intro=tv("Stanford Encyclopedia of Philosophy",28);intro.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(intro);TextView sub=tv("A quiet, focused reader for one of the world's major philosophical reference works.",16);sub.setTextColor(Color.rgb(111,106,97));content.addView(sub);
  addSection("Explore", new String[]{"Featured entries","Table of contents","Recently read","Bookmarks"},new Runnable[]{()->open(HOME),()->open(HOME+"contents.html"),()->showEntries("Recently read","recent"),()->showEntries("Bookmarks","bookmarks")});
  TextView note=tv("Tip\nSearch for an entry such as Aristotle, consciousness, free will, existentialism, or philosophy of mind. Articles open from the official Stanford site. Tap ☆ while reading to bookmark it.",15);note.setPadding(dp(18),dp(28),dp(18),dp(18));content.addView(note);
  setContentView(root); updateStar();
 }
 void addSection(String head,String[] labels,Runnable[] actions){TextView h=tv(head,18);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);content.addView(h);for(int i=0;i<labels.length;i++){TextView x=tv(labels[i]+"  ›",16);final Runnable act=actions[i];x.setOnClickListener(v->act.run());content.addView(x);}}
 void openSearch(String q){if(q.trim().isEmpty())return;String u="https://plato.stanford.edu/search/searcher.html?query="+Uri.encode(q);open(u);}
 void open(String url){ if(web!=null) root.removeView(web); web=new WebView(this); web.setBackgroundColor(dark?Color.rgb(18,18,18):Color.rgb(250,248,243));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setBuiltInZoomControls(false);s.setTextZoom(prefs.getInt("zoom",100));web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return false;}@Override public void onPageFinished(WebView v,String u){inject();String t=v.getTitle();saveEntry("recent",(t==null||t.isEmpty())?u:t,u,10);updateStar();}});web.loadUrl(url); sc.setVisibility(View.GONE); root.addView(web,new LinearLayout.LayoutParams(-1,0,1)); updateStar();}
 void goHome(){if(web!=null){root.removeView(web);web=null;} sc.setVisibility(View.VISIBLE); updateStar();}
 void inject(){if(web==null)return;String bg=dark?"#121212":"#FAF8F3",fg=dark?"#EDEAE4":"#202124",muted=dark?"#B8B2A8":"#5E5A53";String js="javascript:(function(){var s=document.getElementById('sepReaderStyle');if(s)s.remove();s=document.createElement('style');s.id='sepReaderStyle';s.innerHTML='body{background:"+bg+" !important;color:"+fg+" !important;} a{color:"+(dark?"#D8B77A":"#6B4F2A")+" !important;} #header,#footer,.menu,.navigation,.navbar{ } .article{max-width:900px!important;margin:auto!important;}';document.head.appendChild(s);})()";web.evaluateJavascript(js,null);}
 // --- storage: entries are stored one-per-line as "title\u0001url" ---
 List<String> loadList(String key){List<String> l=new ArrayList<>();for(String line:prefs.getString(key,"").split("\n")) if(!line.trim().isEmpty()) l.add(line); return l;}
 void saveList(String key,List<String> l){prefs.edit().putString(key,String.join("\n",l)).apply();}
 void saveEntry(String key,String title,String url,int cap){List<String> l=loadList(key);l.removeIf(e->e.endsWith(SEP+url));l.add(0,title+SEP+url);while(l.size()>cap)l.remove(l.size()-1);saveList(key,l);}
 boolean removeEntry(String key,String url){List<String> l=loadList(key);boolean r=l.removeIf(e->e.endsWith(SEP+url));saveList(key,l);return r;}
 boolean isBookmarked(String url){if(url==null)return false;for(String e:loadList("bookmarks")) if(e.endsWith(SEP+url)) return true; return false;}
 void updateStar(){if(star==null)return; boolean on=web!=null && isBookmarked(web.getUrl()); star.setText(on?"★":"☆");}
 void toggleBookmark(){if(web==null){Toast.makeText(this,"Open an article first, then tap ☆ to save it.",Toast.LENGTH_SHORT).show();return;} String url=web.getUrl(); String t=web.getTitle(); if(t==null||t.isEmpty())t=url; if(isBookmarked(url)){removeEntry("bookmarks",url);Toast.makeText(this,"Removed bookmark",Toast.LENGTH_SHORT).show();}else{saveEntry("bookmarks",t,url,50);Toast.makeText(this,"Bookmarked",Toast.LENGTH_SHORT).show();} updateStar();}
 void showEntries(String title,String key){List<String> l=loadList(key); if(l.isEmpty()){new AlertDialog.Builder(this).setTitle(title).setMessage(key.equals("bookmarks")?"No bookmarks yet. Open an article and tap ☆ to save it here.":"No recent entries yet. Articles you open will appear here.").setPositiveButton("OK",null).show();return;} String[] labels=new String[l.size()];String[] urls=new String[l.size()];for(int i=0;i<l.size();i++){int p=l.get(i).indexOf(SEP);labels[i]=p>=0?l.get(i).substring(0,p):l.get(i);urls[i]=p>=0?l.get(i).substring(p+1):l.get(i);} new AlertDialog.Builder(this).setTitle(title).setItems(labels,(d,which)->open(urls[which])).setNegativeButton(key.equals("bookmarks")?"Clear all":"Close",key.equals("bookmarks")?(d,which)->{saveList("bookmarks",new ArrayList<>());updateStar();}:null).show();}
 @Override public void onBackPressed(){if(web!=null && web.canGoBack())web.goBack();else if(web!=null)goHome();else super.onBackPressed();}
}
